x-services:
  node: &node
    image: apache/kafka:4.0.0

x-env:
  common: &env-common
    KAFKA_CONTROLLER_QUORUM_VOTERS: 1@${CLUSTER_ID:?error}-controller-1:9093,2@${CLUSTER_ID:?error}-controller-2:9093,3@${CLUSTER_ID:?error}-controller-3:9093
    KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
    KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
  controller: &env-controller
    <<: *env-common
    KAFKA_PROCESS_ROLES: controller
    KAFKA_LISTENERS: CONTROLLER://:9093
  broker: &env-broker
    <<: *env-common
    KAFKA_PROCESS_ROLES: broker
    KAFKA_LISTENERS: 'PLAINTEXT://:19092,PLAINTEXT_HOST://:9092'
    KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

x-volumes:
  data: &vol-data
    driver: local

x-depends-on:
  controllers: &depends-on-controllers
    - controller-1
    - controller-2
    - controller-3

name: ${CLUSTER_ID:?error}

services:
  controller-1:
    <<: *node
    container_name: ${CLUSTER_ID:?error}-controller-1
    environment:
      KAFKA_NODE_ID: 1
      <<: *env-controller
    volumes:
      - controller-1-data:/var/lib/kafka/data

  controller-2:
    <<: *node
    container_name: ${CLUSTER_ID:?error}-controller-2
    environment:
      KAFKA_NODE_ID: 2
      <<: *env-controller
    volumes:
      - controller-2-data:/var/lib/kafka/data

  controller-3:
    <<: *node
    container_name: ${CLUSTER_ID:?error}-controller-3
    environment:
      KAFKA_NODE_ID: 3
      <<: *env-controller
    volumes:
      - controller-3-data:/var/lib/kafka/data

  broker-1:
    <<: *node
    container_name: ${CLUSTER_ID:?error}-broker-1
    ports:
      - 29092:9092
    environment:
      KAFKA_NODE_ID: 4
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://${CLUSTER_ID:?error}-broker-1:19092,PLAINTEXT_HOST://localhost:29092'
      <<: *env-broker
    volumes:
      - broker-1-data:/var/lib/kafka/data
    depends_on: *depends-on-controllers

  broker-2:
    <<: *node
    container_name: ${CLUSTER_ID:?error}-broker-2
    ports:
      - 39092:9092
    environment:
      KAFKA_NODE_ID: 5
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://${CLUSTER_ID:?error}-broker-2:19092,PLAINTEXT_HOST://localhost:39092'
      <<: *env-broker
    volumes:
      - broker-2-data:/var/lib/kafka/data
    depends_on: *depends-on-controllers

  broker-3:
    <<: *node
    container_name: ${CLUSTER_ID:?error}-broker-3
    ports:
      - 49092:9092
    environment:
      KAFKA_NODE_ID: 6
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://${CLUSTER_ID:?error}-broker-3:19092,PLAINTEXT_HOST://localhost:49092'
      <<: *env-broker
    volumes:
      - broker-3-data:/var/lib/kafka/data
    depends_on: *depends-on-controllers

networks:
  default:
    name: ${CLUSTER_ID:?error}
    driver: bridge

volumes:
  controller-1-data: *vol-data
  controller-2-data: *vol-data
  controller-3-data: *vol-data
  broker-1-data: *vol-data
  broker-2-data: *vol-data
  broker-3-data: *vol-data
